# Generated by Django 3.0.3 on 2020-08-13 13:47

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(upload_to=www.models.user_directory_path),
        ),
    ]
