# Generated by Django 3.0.3 on 2020-08-16 14:39

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20200813_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=www.models.user_thumbnail_directory_path),
        ),
    ]
