# Generated by Django 3.0.3 on 2020-08-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200818_2348'),
        ('www', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('bundle', models.IntegerField()),
                ('bundle_order', models.IntegerField()),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Video')),
            ],
        ),
    ]
