# Generated by Django 3.0.3 on 2020-08-17 06:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='blog/post'),
        ),
    ]
