# Generated by Django 3.0.3 on 2020-08-17 07:34

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=accounts.models.user_profile_thumbnail_directory_path),
        ),
    ]
