# Generated by Django 3.0.3 on 2020-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200817_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribing',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribing_by',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
