# Generated by Django 3.0.3 on 2020-08-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200818_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribing_by',
        ),
    ]
