# Generated by Django 3.0.3 on 2020-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200818_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribing',
            field=models.CharField(default='[]', max_length=5000),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribing_by',
            field=models.CharField(default='[]', max_length=5000),
        ),
    ]
